FROM quay.io/pypa/manylinux_2_34_x86_64

# Get ready-made dependencies
RUN yum install -y python3 python3-devel python3-pip curl lld clang cmake boost-devel hdf5-devel libzip-devel bzip2-devel ninja-build openssl-devel xz-devel
RUN python3 -m pip install h5py
RUN python3.14 -m pip install pyyaml

RUN mkdir -p /opt/llvm
RUN git clone --depth 1 --branch llvmorg-22.1.2 https://github.com/llvm/llvm-project.git /opt/llvm
RUN mkdir /opt/llvm/build

RUN cmake -G "Ninja" -S /opt/llvm/llvm -B /opt/llvm/build \
    -DCMAKE_BUILD_TYPE=Release \
#    -DLLVM_ENABLE_RTTI \
#    -DLLVM_ENABLE_EH=ON \
#    -DLLVM_ENABLE_LLD=ON \
#    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;flang;lld;lldb;mlir" \
    -DLLVM_ENABLE_RUNTIMES="libc;libunwind;libcxxabi;libcxx;compiler-rt;openmp;flang-rt"

RUN cmake --build /opt/llvm/build
RUN cmake --build /opt/llvm/build --target install
