name: Wheels

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
     - master
  release:
    types:
      - published

env:
  FORCE_COLOR: 3

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Build SDist
      working-directory: pyvcell-fvsolver
      run: pipx run build --sdist

    - name: Check metadata
      working-directory: pyvcell-fvsolver
      run: pipx run twine check dist/*

    - name: artifact upload
      uses: actions/upload-artifact@v4
      with:
        name: cibw-sdist
        path: dist/*.tar.gz
        working-directory: pyvcell-fvsolver


  build_wheels:
    name: Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: build wheel
      uses: pypa/cibuildwheel@v2.17
      with:
        working-directory: pyvcell-fvsolver
      env:
        CIBW_ARCHS_MACOS: universal2
        CIBW_ARCHS_WINDOWS: auto ARM64

    - name: Verify clean directory
      working-directory: pyvcell-fvsolver
      run: git diff --exit-code
      shell: bash

    - uses: actions/upload-artifact@v4
      with:
        name: cibw-wheels-${{ matrix.os }}
        working-directory: pyvcell-fvsolver
        path: wheelhouse/*.whl


  upload_all:
    name: Upload if release
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    environment: pypi
    permissions:
      id-token: write

    steps:
    - uses: actions/setup-python@v5
      with:
        python-version: "3.x"

    - uses: actions/download-artifact@v4
      with:
        working-directory: pyvcell-fvsolver
        pattern: cibw-*
        merge-multiple: true
        path: dist

    - uses: pypa/gh-action-pypi-publish@release/v1
